require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.completion")
require("user.nvim-tree")
require("user.ui")
require("user.autopairs")
require("user.comment")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.toggleterm")
require("user.conform")
require("user.vimtex")
-- require("user.xkbswitch")
require("user.im-select")
